version: "3"
output: prefixed

tasks:
  check:
    deps:
      - check:flake
      - check:nix-unit
      - check:integration-tests

  check:flake:
    cmds:
      - nix flake check
  
  check:nix-unit:
    cmds:
      - nix-unit --flake .#tests {{.CLI_ARGS}}
  
  check:integration-tests:
    sources:
      - integration-tests/**/flake.nix
    cmds:
      - for: sources
        cmd: cd $(dirname {{.ITEM}}); git clean -fdx .; nix develop --no-write-lock-file --command ./test.sh
  
  ci:check:
    deps: [check]
