{
  description = "python-monorepo";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-24.11";
  };

  outputs =
    inputs@{
      flake-utils,
      nixpkgs,
      self,
      ...
    }:
    let
      rising-tide = builtins.getFlake (
        builtins.unsafeDiscardStringContext "path:${self.sourceInfo}?narHash=${self.narHash}"
      );
      perSystemOutputs = flake-utils.lib.eachDefaultSystem (
        system:
        let
          pkgs = import nixpkgs {
            inherit system;
            overlays = [ self.overlays.default ];
          };
          pythonPackages = pkgs.python3.pkgs;
          project = rising-tide.lib.mkProject { inherit pkgs; } {
            name = "python-monorepo-root";
            subprojects = {
              package-1 = import ./projects/package-1/project.nix;
              package-2 = import ./projects/package-2/project.nix;
              package-3 = import ./projects/package-3-with-no-tests/project.nix;
            };
          };
        in
        rec {
          inherit project;
          # This should be generated by the project as well
          packages = { inherit (pythonPackages) package-1 package-2 package-3; };

          devShells = project.devShells;
        }
      );
      systemIndependentOutputs = rising-tide.lib.project.mkSystemIndependentOutputs {
        rootProjectBySystem = perSystemOutputs.project;
      };

    in
    perSystemOutputs
    // {
      inherit (systemIndependentOutputs) overlays pythonOverlays;
      inputs = inputs // {
        inherit rising-tide;
      };
    };
}
