dotenv:
  - .env
version: "3"
output:
  group:
    begin: ::group::{{.ALIAS}}
    end: '::endgroup::'
run: when_changed
tasks:
  build:
    deps:
      - nix-build:_all-project-packages
    desc: Build
  check:
    aliases:
      - lint
      - format
      - fmt
    cmds:
      - task: check:treefmt
    desc: Run all checks
  check:treefmt:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/treefmt --config-file /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-treefmt.toml {{if .CI}} --no-cache {{end}} --tree-root . --on-unmatched debug
    desc: Reformat with treefmt
  check:treefmt:*:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/treefmt --config-file /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-treefmt.toml --formatters {{.FORMATTER}} {{if .CI}} --no-cache {{end}} --tree-root . --on-unmatched debug
    desc: Reformat with treefmt formatter {{.FORMATTER}}
    label: check:treefmt:{{.FORMATTER}}
    prefix: check:treefmt:{{.FORMATTER}}
    vars:
      FORMATTER: '{{index .MATCH 0}}'
  ci:
    cmds:
      - task: ci:check-derivation-unchanged
      - task: ci:check-not-dirty
    deps:
      - build
      - check
      - test
    desc: Run CI workflow
  ci:check-derivation-unchanged:
    cmds:
      - nix build --out-link build/check-derivation-unchanged/original.drv $(nix derivation show .#_all-project-packages | /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/jq --raw-output 'keys[]')
      - echo >> flake.nix
      - defer: truncate --size=-1 flake.nix
      - nix build --out-link build/check-derivation-unchanged/modified.drv $(nix derivation show .#_all-project-packages | /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/jq --raw-output 'keys[]')
      - |
        if [ "$(readlink build/check-derivation-unchanged/original.drv)" != "$(readlink build/check-derivation-unchanged/modified.drv)" ]; then
          echo 'Derivation .#_all-project-packages has changed';
          /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/nix-diff build/check-derivation-unchanged/original.drv build/check-derivation-unchanged/modified.drv
        fi
    desc: Check if the derivation has changed
  ci:check-not-dirty:
    cmds:
      - git status
      - git diff-files --compact-summary --exit-code .
    desc: Check if the the git repo is dirty
  nix-build:*:
    cmds:
      - nix build --show-trace --log-lines 500 .?submodules=1#{{.PACKAGE}}
    desc: Build a package with `nix build`
    label: nix-build:{{.PACKAGE}}
    prefix: nix-build:{{.PACKAGE}}
    vars:
      PACKAGE: '{{index .MATCH 0}}'
  pre-commit:
    deps:
      - check:treefmt:deadnix,keep-sorted,mdformat,nixfmt-rfc-style,ripsecrets,shellcheck,shfmt,taplo
    desc: Run all pre-commit checks
  test:
    desc: Run all tests
    internal: true
  tool:deadnix:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/deadnix  {{.CLI_ARGS}}
    desc: Run deadnix. Additional CLI arguments after `--` are forwarded to deadnix
  tool:keep-sorted:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/keep-sorted {{.CLI_ARGS}}
    desc: Run keep-sorted. Additional CLI arguments after `--` are forwarded to keep-sorted
  tool:mdformat:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/mdformat {{.CLI_ARGS}}
    desc: Run mdformat. Additional CLI arguments after `--` are forwarded to mdformat
  tool:nil:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/nil {{.CLI_ARGS}}
    desc: Run nil. Additional CLI arguments after `--` are forwarded
  tool:nixfmt-rfc-style:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/nixfmt {{.CLI_ARGS}}
    desc: Run nixfmt-rfc-style. Additional CLI arguments after `--` are forwarded
  tool:ripsecrets:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/ripsecrets {{.CLI_ARGS}}
    desc: Run ripsecrets. Additional CLI arguments after `--` are forwarded to ripsecrets
  tool:shellcheck:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/shellcheck --rcfile /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-shellcheckrc {{.CLI_ARGS}}
    desc: Run shellcheck. Additional CLI arguments after `--` are forwarded to shellcheck
  tool:shfmt:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/shfmt --simplify --indent 2 --case-indent --binary-next-line {{.CLI_ARGS}}
    desc: Run shfmt. Additional CLI arguments after `--` are forwarded to shfmt
  tool:taplo:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/taplo {{.CLI_ARGS}}
    desc: Run taplo. Additional CLI arguments after `--` are forwarded to taplo
    env:
      TAPLO_CONFIG: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-taplo.toml
  tool:treefmt:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/treefmt --config-file /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-treefmt.toml {{.CLI_ARGS}} --tree-root . --on-unmatched debug
    desc: Run treefmt. Additional CLI arguments after `--` are forwarded to treefmt
