version: "3"
output: prefixed
run: when_changed
tasks:
  build:
    desc: Build
    internal: true
  check:
    aliases:
      - lint
      - format
      - fmt
    deps:
      - check:treefmt
    desc: Run all checks
  check:treefmt:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/treefmt --config-file /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-treefmt.toml {{if .CI}} --ci {{end}} --tree-root . --on-unmatched debug
    desc: Reformat with treefmt
  test:
    desc: Run all tests
    internal: true
  tool:deadnix:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/deadnix  {{.CLI_ARGS}}
    desc: Run deadnix. Additional CLI arguments after `--` are forwarded to deadnix
  tool:keep-sorted:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/keep-sorted {{.CLI_ARGS}}
    desc: Run keep-sorted. Additional CLI arguments after `--` are forwarded to keep-sorted
  tool:mdformat:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/mdformat {{.CLI_ARGS}}
    desc: Run mdformat. Additional CLI arguments after `--` are forwarded to mdformat
  tool:nil:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/nil {{.CLI_ARGS}}
    desc: Run nil. Additional CLI arguments after `--` are forwarded
  tool:nixfmt-rfc-style:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/nixfmt {{.CLI_ARGS}}
    desc: Run nixfmt-rfc-style. Additional CLI arguments after `--` are forwarded
  tool:ripsecrets:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/ripsecrets {{.CLI_ARGS}}
    desc: Run ripsecrets. Additional CLI arguments after `--` are forwarded to ripsecrets
  tool:shellcheck:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/shellcheck --rcfile /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-shellcheckrc {{.CLI_ARGS}}
    desc: Run shellcheck. Additional CLI arguments after `--` are forwarded to shellcheck
  tool:shfmt:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/shfmt --simplify --indent 2 --case-indent --binary-next-line {{.CLI_ARGS}}
    desc: Run shfmt. Additional CLI arguments after `--` are forwarded to shfmt
  tool:taplo:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/taplo {{.CLI_ARGS}}
    desc: Run taplo. Additional CLI arguments after `--` are forwarded to taplo
    env:
      TAPLO_CONFIG: /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-taplo.toml
  tool:treefmt:
    cmds:
      - /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee/bin/treefmt --config-file /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-treefmt.toml {{.CLI_ARGS}} --tree-root . --on-unmatched debug
    desc: Run treefmt. Additional CLI arguments after `--` are forwarded to treefmt
