name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history so that protobuf API compatibility can be checked
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `task ci`
        run: nix develop --command task ci
      - run: >
          set +x;
          git --version;
          git diff -u;
          git diff-files --quiet;
          git diff-files -u --compact-summary --exit-code;
